### ISSUE TITLE
Create subject - display success

### ISSUE THREAD

**Issue by waedi** [psit4-lamas/PSIT4-LaMaS#107]
As I user I want to see a success message if the lecture was created successfully, so that I know that the lecture has been created

**Task**:
- [ ] createSubject() must return a promise
- [x] successMessage should check for this promise

**Acceptance criteria**:
- [x] The success message will only be displayed if the subject was created succesfully
- [x] The success message contains the name of the subject and the tutors assigned to it.
