### ISSUE TITLE
Comment Video

### ISSUE THREAD

**Issue by Nesschen** [psit4-lamas/PSIT4-LaMaS#22]
As a student, I want to comment a video, so that I can ask questions.

**Acceptance criteria**:
- [x] the user can comment a video
- [x] the comment is saved correctly on the server
- [x] the comment is shown below the video
