### ISSUE TITLE
Quiz During Videos

### ISSUE THREAD

**Issue by wumacH** [psit4-lamas/PSIT4-LaMaS#30]
As a tutor, i want to attach questions to videos, so that the students can learn from them.

**Acceptance criteria**:
- [ ] the user can add questions
- [ ] the user can add a time code or slide number for the question
- [ ] if the user opens a slide set, the questions are shown on the correct slide or during the correct time code of the video
- [ ] if the questions can't be loaded from the server due to an error, the user gets notified with a warning, but the videos and slides can be watched anyway
